# Generated by Django 4.2.7 on 2024-12-02 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_login_attempts'),
        ('recruitment', '0002_alter_recruitment_selectors'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='optional_motivation',
            field=models.BooleanField(default=False, help_text='Motivation letter not mandatory for candidate creation'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='selectors',
            field=models.ManyToManyField(blank=True, help_text='Only these selectors can view and manage this recruitment if they are marked as selectors', related_name='recruitment_selections', to='employee.employee', verbose_name='Selectors'),
        ),
    ]
