# Generated by Django 4.2.7 on 2024-12-23 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0003_recruitment_optional_motivation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stage',
            name='stage_type',
            field=models.CharField(choices=[('applied', 'Applied'), ('test', 'Test'), ('interview', 'Interview'), ('cancelled', 'Cancelled'), ('hired', 'Hired'), ('selector', 'Demandeur')], default='interview', max_length=20),
        ),
    ]
