# Generated by Django 4.2.7 on 2025-01-08 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_login_attempts'),
        ('recruitment', '0004_alter_stage_stage_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='generate_form',
            field=models.BooleanField(default=False, help_text='Check to automatically generate a new Google Form', verbose_name='Generate Google Form'),
        ),
        migrations.AddField(
            model_name='recruitment',
            name='google_form_url',
            field=models.URLField(blank=True, help_text='URL of the linked Google Form', max_length=500, null=True, verbose_name='Google Form URL'),
        ),
        migrations.AlterField(
            model_name='recruitment',
            name='selectors',
            field=models.ManyToManyField(blank=True, help_text='Only these selectors can view and manage this recruitment if they are marked as selectors', related_name='recruitment_selections', to='employee.employee', verbose_name='Demandeur'),
        ),
    ]
