# Generated by Django 4.2.7 on 2025-01-21 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_recruitment_generate_form_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='duration',
            field=models.IntegerField(default=60, validators=[django.core.validators.MinValueValidator(15)], verbose_name='Duration (minutes)'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Calendar Event ID'),
        ),
        migrations.AddField(
            model_name='interviewschedule',
            name='google_meet_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Meet Link'),
        ),
    ]
