# Generated by Django 4.2.7 on 2025-01-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_interviewschedule_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewschedule',
            name='attendees',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='google_event_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
