# Generated by Django 4.2.7 on 2025-01-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_alter_candidate_created_by_alter_candidate_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='ai_analysis_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Analysis Details'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Analysis Status'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_analysis_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Analysis'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='ai_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI Score'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='ai_analysis_details',
            field=models.JSONField(blank=True, null=True, verbose_name='Analysis Details'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='ai_analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20, verbose_name='Analysis Status'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='ai_analysis_timestamp',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Analysis'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='ai_score',
            field=models.FloatField(blank=True, null=True, verbose_name='AI Score'),
        ),
    ]
