# Generated by Django 5.1.6 on 2025-05-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0011_aiconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconfiguration',
            name='analysis_prompt',
            field=models.TextField(default='IMPORTANT: Répondez uniquement avec un JSON valide sans texte additionnel.\n        Vous êtes un expert RH qui analyse des CV pour évaluer l\'adéquation avec un poste.\n        \n        Critères d\'évaluation:\n        1. Pertinence du domaine (30%) - Si le domaine ne correspond PAS DU TOUT au poste, score=0\n        2. Expérience professionnelle (25%) - Durée, postes similaires, responsabilités\n        3. Formation/Éducation (20%) - Diplômes pertinents, niveau d\'études\n        4. Compétences techniques (15%) - Adéquation avec les technologies requises\n        5. Certifications/Projets (10%) - Certifications spécifiques, projets pertinents\n        \n        Description du poste à analyser:\n        {}\n        \n        Format JSON requis (OBLIGATOIRE):\n        {{\n            "job_matching": {{\n                "is_relevant": true/false,\n                "reason": "Expliquer pourquoi le CV correspond ou non au poste"\n            }},\n            "score": 0-100,\n            "details": {{\n                "education": "Analyse de la formation",\n                "experience": "Analyse de l\'expérience", \n                "technical_skills": "Analyse des compétences techniques",\n                "certifications": "Certifications et projets pertinents"\n            }},\n            "strengths": ["Point fort 1", "Point fort 2"],\n            "areas_for_improvement": ["Amélioration 1", "Amélioration 2"]\n        }}', help_text="Prompt utilisé pour l'analyse des CV", verbose_name='Analysis Prompt'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='api_key',
            field=models.CharField(help_text="Clé API together pour l'analyse des CV", max_length=255, verbose_name='together API Key'),
        ),
        migrations.AlterField(
            model_name='aiconfiguration',
            name='model_name',
            field=models.CharField(default='deepseek-ai/DeepSeek-V3', help_text='Nom du modèle IA à utiliser', max_length=100, verbose_name='Model Name'),
        ),
    ]
