# Generated by Django 5.1.6 on 2025-05-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0012_alter_aiconfiguration_analysis_prompt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruitment',
            name='validity_duration',
            field=models.IntegerField(choices=[(30, '30 jours'), (45, '45 jours'), (60, '60 jours'), (90, '90 jours'), (120, '120 jours'), (180, '180 jours'), (365, '1 an'), (0, 'Personnalisé')], default=60, help_text="Durée de validité de l'offre en jours", verbose_name='Durée de validité (jours)'),
        ),
    ]
