# Generated by Django 5.1.6 on 2025-05-29 04:17

import django.db.models.deletion
import recruitment.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_announcement_is_active_and_more'),
        ('recruitment', '0013_recruitment_validity_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivacyPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('name', models.CharField(help_text='Nom de la politique de confidentialité', max_length=100, verbose_name='Policy Name')),
                ('content_type', models.CharField(choices=[('text', 'Text'), ('pdf', 'PDF')], default='text', max_length=10, verbose_name='Content Type')),
                ('text_content', models.TextField(blank=True, help_text='Contenu textuel de la politique', null=True, verbose_name='Text Content')),
                ('pdf_file', models.FileField(blank=True, help_text='Fichier PDF de la politique', null=True, upload_to='recruitment/privacy_policies/', validators=[recruitment.models.validate_pdf], verbose_name='PDF File')),
                ('is_default', models.BooleanField(default=False, help_text="Politique par défaut si aucune n'est assignée à la filiale", verbose_name='Default Policy')),
                ('companies', models.ManyToManyField(blank=True, help_text='Filiales utilisant cette politique', to='base.company', verbose_name='Companies')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'verbose_name': 'Privacy Policy',
                'verbose_name_plural': 'Privacy Policies',
            },
        ),
        migrations.CreateModel(
            name='CandidatePrivacyConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Est actif')),
                ('consented_at', models.DateTimeField(auto_now_add=True, verbose_name='Consent Date')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_consent', to='recruitment.candidate', verbose_name='Candidate')),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
                ('policy', models.ForeignKey(help_text='Politique acceptée par le candidat', on_delete=django.db.models.deletion.PROTECT, to='recruitment.privacypolicy', verbose_name='Privacy Policy')),
            ],
            options={
                'verbose_name': 'Privacy Consent',
                'verbose_name_plural': 'Privacy Consents',
            },
        ),
    ]
