# Generated by Django 5.1.6 on 2025-05-29 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_privacypolicy_candidateprivacyconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, help_text='Indicates if the candidate accepted the privacy policy', verbose_name='Privacy Policy Accepted'),
        ),
        migrations.AddField(
            model_name='historicalcandidate',
            name='privacy_policy_accepted',
            field=models.BooleanField(default=False, help_text='Indicates if the candidate accepted the privacy policy', verbose_name='Privacy Policy Accepted'),
        ),
    ]
