# Generated by Django 5.1.6 on 2025-05-30 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0016_skillzoneimporthistory_alter_skillzone_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillzonecandidate',
            name='skill_zone_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skillzonecandidate_set', to='recruitment.skillzone', verbose_name='Skill Zone'),
        ),
    ]
