# Generated by Django 5.1.6 on 2025-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_automations', '0006_alter_mailautomation_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailautomation',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='mailautomation',
            name='model',
            field=models.CharField(choices=[], max_length=100),
        ),
    ]
