# Generated by Django 5.1.6 on 2025-05-23 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_automations', '0008_remove_model_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailautomation',
            name='model',
            field=models.CharField(max_length=100),
        ),
    ]
