# Generated by Django 5.1.6 on 2025-05-23 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_actiontype_block_option_and_more'),
        ('horilla_automations', '0009_alter_mailautomation_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailautomation',
            name='also_sent_to',
            field=models.ManyToManyField(blank=True, help_text='The employees selected here will receive the email as Cc.', related_name='automation_cc_emails', to='employee.employee', verbose_name='Also Sent to'),
        ),
    ]
