# Generated by Django 4.2.7 on 2024-11-29 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_login_attempts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='login_attempts',
        ),
    ]
