# Generated by Django 4.2.7 on 2025-01-09 10:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_remove_employee_login_attempts'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the password was changed'),
        ),
    ]
