# Generated by Django 4.2.7 on 2025-01-13 08:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_employee_failed_login_attempts_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['employee_first_name'], 'permissions': (('change_ownprofile', 'Update own profile'), ('view_ownprofile', 'View Own Profile'), ('can_unblock_users', 'Can unblock locked user accounts'))},
        ),
        migrations.AlterField(
            model_name='employee',
            name='failed_login_attempts',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of consecutive failed login attempts'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='last_password_change',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='Last time the password was changed'),
        ),
    ]
