# Generated by Django 5.1.6 on 2025-03-01 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_announcement_is_active_and_more'),
        ('candidate_portal', '0001_initial'),
        ('recruitment', '0010_alter_candidate_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=128, verbose_name='Mot de passe')),
                ('first_name', models.CharField(max_length=150, verbose_name='Prénom')),
                ('last_name', models.CharField(max_length=150, verbose_name='Nom')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Dernière connexion')),
            ],
            options={
                'verbose_name': 'Authentification Candidat',
                'verbose_name_plural': 'Authentifications Candidats',
            },
        ),
        migrations.RemoveField(
            model_name='conversationthread',
            name='candidate_user',
        ),
        migrations.AlterModelOptions(
            name='conversationthread',
            options={'verbose_name': 'Conversation', 'verbose_name_plural': 'Conversations'},
        ),
        migrations.AlterModelOptions(
            name='savedjob',
            options={'verbose_name': 'Offre sauvegardée', 'verbose_name_plural': 'Offres sauvegardées'},
        ),
        migrations.AlterModelOptions(
            name='verificationtoken',
            options={'verbose_name': 'Token de vérification', 'verbose_name_plural': 'Tokens de vérification'},
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de création'),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Actif'),
        ),
        migrations.AlterField(
            model_name='conversationthread',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='recruitment.recruitment', verbose_name='Recrutement'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Contenu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False, verbose_name='Lu'),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_id',
            field=models.IntegerField(verbose_name="ID de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='message',
            name='sender_type',
            field=models.CharField(choices=[('candidate', 'Candidat'), ('recruiter', 'Recruteur')], max_length=10, verbose_name="Type d'expéditeur"),
        ),
        migrations.AlterField(
            model_name='message',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='candidate_portal.conversationthread', verbose_name='Conversation'),
        ),
        migrations.AlterField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horodatage'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='date_saved',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date de sauvegarde'),
        ),
        migrations.AlterField(
            model_name='savedjob',
            name='recruitment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recruitment.recruitment', verbose_name='Recrutement'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='conversationthread',
            name='candidate_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='candidate_portal.candidateauth', verbose_name='Candidat'),
        ),
        migrations.AddField(
            model_name='savedjob',
            name='candidate_auth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_jobs', to='candidate_portal.candidateauth', verbose_name='Candidat'),
        ),
        migrations.AlterUniqueTogether(
            name='savedjob',
            unique_together={('candidate_auth', 'recruitment')},
        ),
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='Téléphone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('candidate_auth', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='candidate_portal.candidateauth', verbose_name='Authentification')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.company', verbose_name='Entreprise')),
            ],
            options={
                'verbose_name': 'Profil Candidat',
                'verbose_name_plural': 'Profils Candidats',
            },
        ),
        migrations.CreateModel(
            name='CandidateSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('candidate_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='candidate_portal.candidateauth', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Session Candidat',
                'verbose_name_plural': 'Sessions Candidats',
            },
        ),
        migrations.DeleteModel(
            name='CandidateUser',
        ),
        migrations.RemoveField(
            model_name='savedjob',
            name='user',
        ),
    ]
