# Generated by Django 5.1.6 on 2025-03-02 02:18

import candidate_portal.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_portal', '0002_candidateauth_and_more'),
        ('recruitment', '0010_alter_candidate_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='availability_date',
            field=models.DateField(blank=True, null=True, verbose_name='Disponibilité'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='biography',
            field=models.TextField(blank=True, null=True, verbose_name='Biographie'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ville'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Pays'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Monsieur'), ('female', 'Madame')], default='male', max_length=10, verbose_name='Genre'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='headline',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Titre professionnel'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, null=True, verbose_name='Profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='candidate_photos/', verbose_name='Photo de profil'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='portfolio_url',
            field=models.URLField(blank=True, null=True, verbose_name='Site web / Portfolio'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_job_type',
            field=models.CharField(choices=[('full_time', 'Temps plein'), ('part_time', 'Temps partiel'), ('contract', 'Contrat'), ('internship', 'Stage'), ('any', 'Tous types')], default='any', max_length=50, verbose_name="Type d'emploi recherché"),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='preferred_work_location',
            field=models.CharField(choices=[('on_site', 'Sur site'), ('remote', 'Télétravail'), ('hybrid', 'Hybride'), ('any', 'Indifférent')], default='any', max_length=50, verbose_name='Mode de travail préféré'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='skills',
            field=models.ManyToManyField(blank=True, related_name='candidate_profiles', to='recruitment.skill', verbose_name='Compétences'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='years_of_experience',
            field=models.PositiveIntegerField(default=0, verbose_name="Années d'expérience"),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Code postal'),
        ),
        migrations.AlterField(
            model_name='candidateprofile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='CandidateDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Titre')),
                ('document_type', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Lettre de motivation'), ('diploma', 'Diplôme'), ('certificate', 'Certificat'), ('other', 'Autre')], default='other', max_length=20, verbose_name='Type de document')),
                ('file', models.FileField(upload_to=candidate_portal.models.document_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])], verbose_name='Fichier')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'ajout")),
                ('is_public', models.BooleanField(default=False, verbose_name='Visible par les recruteurs')),
                ('candidate_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='candidate_portal.candidateauth', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=100, verbose_name='Diplôme/Formation')),
                ('institution', models.CharField(max_length=100, verbose_name='Établissement')),
                ('field_of_study', models.CharField(blank=True, max_length=100, null=True, verbose_name="Domaine d'études")),
                ('start_year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)], verbose_name='Année de début')),
                ('end_year', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1950), django.core.validators.MaxValueValidator(2050)], verbose_name='Année de fin')),
                ('currently_studying', models.BooleanField(default=False, verbose_name='En cours')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='candidate_portal.candidateauth', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Formation',
                'verbose_name_plural': 'Formations',
                'ordering': ['-start_year'],
            },
        ),
        migrations.CreateModel(
            name='CandidateExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100, verbose_name='Intitulé du poste')),
                ('company', models.CharField(max_length=100, verbose_name='Entreprise')),
                ('industry', models.CharField(blank=True, max_length=100, null=True, verbose_name="Secteur d'activité")),
                ('start_date', models.DateField(verbose_name='Date de début')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Date de fin')),
                ('currently_working', models.BooleanField(default=False, verbose_name='Emploi actuel')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate_auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='candidate_portal.candidateauth', verbose_name='Candidat')),
            ],
            options={
                'verbose_name': 'Expérience professionnelle',
                'verbose_name_plural': 'Expériences professionnelles',
                'ordering': ['-start_date'],
            },
        ),
    ]
