# Generated by Django 5.1.6 on 2025-03-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidate_portal', '0003_candidateprofile_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='application_updates',
            field=models.BooleanField(default=True, verbose_name='Mises à jour de candidature'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='email_notifications',
            field=models.BooleanField(default=True, verbose_name='Notifications par e-mail'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='interview_schedules',
            field=models.BooleanField(default=True, verbose_name="Planification d'entretien"),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='job_recommendations',
            field=models.BooleanField(default=True, verbose_name='Offres recommandées'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='new_messages',
            field=models.BooleanField(default=True, verbose_name='Nouveaux messages'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='notification_frequency',
            field=models.CharField(choices=[('immediately', 'Immédiatement'), ('daily', 'Résumé quotidien'), ('weekly', 'Résumé hebdomadaire')], default='immediately', max_length=20, verbose_name='Fréquence des notifications'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='profile_visible',
            field=models.BooleanField(default=True, verbose_name='Profil visible'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='share_contact_info',
            field=models.BooleanField(default=True, verbose_name='Partager coordonnées'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='share_education',
            field=models.BooleanField(default=True, verbose_name='Partager formation'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='share_experience',
            field=models.BooleanField(default=True, verbose_name='Partager expérience'),
        ),
    ]
