# Generated by Django 5.1.6 on 2025-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horilla_views', '0002_alter_activegroup_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activegroup',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='activetab',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='activeview',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='savedfilter',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
        migrations.AlterField(
            model_name='togglecolumn',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
    ]
