# Generated by Django 5.1.6 on 2025-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biometric', '0002_alter_biometricdevices_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biometricdevices',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est actif'),
        ),
    ]
