# Generated by Django 5.1.6 on 2025-02-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='notification',
            new_name='notificatio_recipie_8bedf2_idx',
            old_fields=('recipient', 'unread'),
        ),
    ]
