# Generated by Django 4.2.7 on 2025-01-14 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_attendanceovertime_year'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PenaltyAccount',
        ),
    ]
