# Generated by Django 4.2.7 on 2025-01-21 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('employee', '0005_alter_employee_options_and_more'),
        ('attendance', '0004_delete_penaltyaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PenaltyAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created At')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('minus_leaves', models.FloatField(default=0.0, null=True)),
                ('deduct_from_carry_forward', models.BooleanField(default=False)),
                ('penalty_amount', models.FloatField(default=0.0, null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('employee_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='penalty_set', to='employee.employee', verbose_name='Employee')),
                ('late_early_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.attendancelatecomeearlyout')),
                ('leave_request_id', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='leave.leaverequest')),
                ('leave_type_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='leave.leavetype', verbose_name='Leave type')),
                ('modified_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_modified_by', to=settings.AUTH_USER_MODEL, verbose_name='Modified By')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
